### ISSUE TITLE
C9 如何提交更新到github相关问题

### ISSUE THREAD

**Issue by weizhou-chaojixx** [PENGZhaoqing/CourseSelect#11]
在C9打开了fork队长后的工程文件以后，自己做了修改以后如何提交自己的更改分支到队长？具体步骤如何操作麻烦助教说稍微详细一点谢谢了。
还有如何可以查看自己和其他组员对这个项目整体的贡献情况？

**Comment by PENGZhaoqing** [comment]
在项目目录下输入 `git add *`

**Comment by PENGZhaoqing** [comment]
接着`git commit -m "update something"`

**Comment by PENGZhaoqing** [comment]
然后 `git push`

成功后，可以在自己的github页面看到刚才自己的改动

**Comment by PENGZhaoqing** [comment]
然后就可以pull request了

主分支（队长）同意后，就可以发现主分支的contributor多了一个人，点进去，就能看到各自的贡献程度了

**Comment by tangmaomao16** [comment]
请老师举实例示范如何在c9平台上做github的小组项目？
老师，我的电脑是windows操作系统，我用cs50网站账号连接到c9平台。我的学习小组在github中已经新建了一个项目，我已经中github网站中fork了那个项目。请问我如何在c9平台上获得那个项目的所有文件，以及修改后发回到github网站中，最后的代码文件和运行演示在哪看呢？

**Comment by PENGZhaoqing** [comment]
运行`git clone github_project_url`从你的github里提取代码

**Comment by PENGZhaoqing** [comment]
在c9中修改代码后，运行下面三句：

```
git add *
git commit -m "what ever"
git push 
```

能够把自己的修改的部分传回你自己的github账号里，再点击pull request能够把你的修改跟你的组长合并

代码文件肯定在c9中看啊，去看教程一吧 @tangmaomao16
