### ISSUE TITLE
中文教程2中，理解Rails框架有困难，官方指南-简易博客Rails 入门中的问题

### ISSUE THREAD

**Issue by cuifeng1993** [PENGZhaoqing/CourseSelect#12]
![image](https://cloud.githubusercontent.com/assets/22235079/19213200/75e43fd6-8d97-11e6-911b-17a1be226894.png)
请问这里怎么创建文章资源？谢谢！

**Comment by PENGZhaoqing** [comment]
`resources :articles`
这一句已经是在创建文章资源了
汉语翻译过来不是 资源：文章 么

**Comment by PENGZhaoqing** [comment]
你可以运行 `rake routes`，看有没有这句话会有什么不同的输出

**Comment by cuifeng1993** [comment]
谢谢老师！我按老师说的做了，明白博客中定义资源的语句了！
![image](https://cloud.githubusercontent.com/assets/22235079/19213278/0e604eb0-8d9a-11e6-93a1-780d9612fa1f.png)
我按博客中定义资源的图片，把之前的get 'welcome/index'删掉了！我先研究研究！有问题我再请教老师！！！再次感谢！！！

**Comment by cuifeng1993** [comment]
![image](https://cloud.githubusercontent.com/assets/22235079/19270412/81669d60-8ff2-11e6-8b99-8c0b3a278c34.png)
老师，您好！图片中的命令创建了一系列文件，包括控制器welcome和方法index。我想问如果一开始只创建了控制器，而没有创建方法，如下图：
![image](https://cloud.githubusercontent.com/assets/22235079/19270555/33af9b0c-8ff3-11e6-8224-60be28dc6b72.png)
这个时候如何单独创建方法文件？如下图
![image](https://cloud.githubusercontent.com/assets/22235079/19270545/2782b1fc-8ff3-11e6-8b99-a78ff37f15a6.png)
麻烦老师了！

**Comment by PENGZhaoqing** [comment]
最简单手动创建，直接去文件目录下，新建txt文件（什么样的都行），然后把文件的名改为`new.html.erb` ，注意`.html.erb`是后缀
