### ISSUE TITLE
教程二建表结果疑问

### ISSUE THREAD

**Issue by ChenHao19931** [PENGZhaoqing/CourseSelect#14]
请问执行最后一句命令后，未出现add_index(:users, :email, {:unique=>true}) -> 0.0011s这条结果，是什么原因呢？谢谢

**Comment by PENGZhaoqing** [comment]
你先检查你的`db/migrate/20160920163927_create_users.rb`有没有这句：

`add_index :users, :email, unique: true`

如果有，你先运行`rake db：migrate：reset`再运行`rake db：seed`

**Comment by ChenHao19931** [comment]
第一句在文件中存在。依次执行后两句，分别显示为
rake aborted!
Don't know how to build task 'db：migrate：reset' (see --tasks)
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
rake aborted!
Don't know how to build task 'db：seed' (see --tasks)
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in`<top (required)>'
(See full trace by running task with --trace)
未能跑通

**Comment by PENGZhaoqing** [comment]
我的分号用的是中文的`：`，你换成`:`就行了

**Comment by ChenHao19931** [comment]
谢谢，已解决
