### ISSUE TITLE
请教对于正则表达式的理解

### ISSUE THREAD

**Issue by tangmaomao16** [PENGZhaoqing/CourseSelect#15]
老师，正则表达式的主要意义是在某些语句中搜索或替换某些字符，对吗？
我有时候看不懂正则表达式里的 / 或 \ 或 #，怎么解读比较好？

**Comment by PENGZhaoqing** [comment]
正则表达式主要目的是用来匹配目标字符串并筛选出具有特定特征的字符串

做文本处理用的比较多，一般了解一下常用的即可，若要系统学习，可以看下面：
http://www.jb51.net/tools/zhengze.html
