### ISSUE TITLE
请教关于学生与老师账号互通的问题

### ISSUE THREAD

**Issue by DetaiLC** [PENGZhaoqing/CourseSelect#16]
老师您好:
       我想请教一下如何添加学生端与老师端的通信，是否和创建成绩的思路一样，谢谢老师

**Comment by PENGZhaoqing** [comment]
你指的通信是指的留言吗，就像我们现在的对话一样

**Comment by DetaiLC** [comment]
是的，就像我们这样的对话

**Comment by PENGZhaoqing** [comment]
这就跟我发了个帖子，然后下面有人留言一样，

首先你要有个post模型，多对一关联用户：一个用户有很多posts，一个post属于一个用户。
然后post下面有留言，留言你可以用message模型，多对一关联post：一个post有很多messages，一个message属于一个post；同时多对一关联用户：一个message属于一个用户，一个用户有很多messages

把关联关系想清楚了就可以想想如何用控制器和视图展示了，我上面说仅供参考，并不是最简单的设计

推荐你看https://www.railstutorial.org/book/user_microposts

**Comment by DetaiLC** [comment]
啊非常感谢～

**Comment by DetaiLC** [comment]
老师能否再请教一个问题，如果想要实现排序，我的想法是通过设置一个按钮，传递一个参数作为if的判断，然后选择执行像这样的按照课程号的排序，<% @course.order(course_code: :asc).each do |course| %>，但是我不清楚这样该怎么写。

**Comment by PENGZhaoqing** [comment]
http://stackoverflow.com/questions/18848564/rails-how-to-sort-the-array-of-active-records-by-created-at

**Comment by PENGZhaoqing** [comment]
你的想法是没有问题的，调用对的方法传入对的参数就可以实现

**Comment by PENGZhaoqing** [comment]
http://stackoverflow.com/questions/4514265/help-with-sorting-records-in-ruby-on-rails

**Comment by DetaiLC** [comment]
谢谢～

**Comment by DetaiLC** [comment]
![screenshot from 2016-10-31 16-26-04](https://cloud.githubusercontent.com/assets/18488222/19848215/e556a5a6-9f86-11e6-9b99-899500cef3fe.png)
老师，不好意思再次打扰您一下，我在User的迁移中增加了t.string :bad, t.string :contest，在rake db:seed后，用管理员账号登陆后，就进入不了控制面板了，

**Comment by PENGZhaoqing** [comment]
最简单的解决方法（如果你数据库里没什么数据），运行 rake db:migrate:reset，然后再运行rake db:seed

**Comment by DetaiLC** [comment]
可是我已经删除数据库，再建立数据库了，还是这样子

**Comment by PENGZhaoqing** [comment]
那就跟数据迁移没有什么关系，问题不是在这里，你看看你有没有改动其他的地方，这个错误是在说没有找到current_user这个方法，我是在Session_helper中定义的这个方法，如果要在控制器中使用，需要在控制器中加入include Session_helper这一句

**Comment by DetaiLC** [comment]
嗯嗯我尝试一下，谢谢啦

**Comment by DetaiLC** [comment]
老师，不好意思，又来打扰0 0，请问一下有的时候，控制面板里面创建新用户的时候，没有输入密码这个选项是什么原因

**Comment by PENGZhaoqing** [comment]
没有吗，不可能吧，，，如果你有相应的代码的话

**Comment by DetaiLC** [comment]
管理员就是admin那个gem咯，没有什么要改的地方的吧？

**Comment by PENGZhaoqing** [comment]
rails_admin里也有很多可以自己自定义的地方，现在来说够用

**Comment by DetaiLC** [comment]
我发现了，不知道什么原因，我登录老师您的demo的时候也没有password这个选项=_=

**Comment by PENGZhaoqing** [comment]
哦哦，我看到了，因为我的用户模型里只有一个Password digest字段，这个字段里储存着加密后的一个token，这个token是根据你填的password自动生成的

**Comment by PENGZhaoqing** [comment]
所以创建新用户，还是回到应用去注册吧
