### ISSUE TITLE
关于教程三调试结果的疑问

### ISSUE THREAD

**Issue by ChenHao19931** [PENGZhaoqing/CourseSelect#17]
根据教程三调试后，结果如图所示，页面为白色，仅有设定的功能项。启动run project后，相应结果如下所示，请问是什么原因？谢谢
Started GET "/" for 121.195.114.58 at 2016-11-02 06:23:28 +0000
Cannot render console from 121.195.114.58! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Rails::WelcomeController#index as HTML
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/templates/rails/welcome/index.html.erb (2.1ms)
Completed 200 OK in 27ms (Views: 14.3ms | ActiveRecord: 0.0ms)

Started GET "/courses/new" for 121.195.114.58 at 2016-11-02 06:23:48 +0000
Cannot render console from 121.195.114.58! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by CoursesController#new as HTML
  Rendered courses/_form.html.erb (22.7ms)
  Rendered courses/new.html.erb within layouts/application (26.7ms)
Completed 200 OK in 368ms (Views: 344.6ms | ActiveRecord: 0.6ms)

Started GET "/stylesheets/application.css" for 121.195.114.58 at 2016-11-02 06:23:48 +0000
Cannot render console from 121.195.114.58! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.6ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/routes/_table.html.erb (27.8ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.8ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (66.3ms)

**Comment by ChenHao19931** [comment]
![qq 20161102141957](https://cloud.githubusercontent.com/assets/22374566/19919350/22fa83d2-a10d-11e6-8594-03f59c928247.png)

**Comment by PENGZhaoqing** [comment]
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):

你的log中这一句反应了问题，css文件没有被服务器找到

**Comment by PENGZhaoqing** [comment]
你去对照我的`app/assets/stylesheets/`下的文件，以及Gemfile里，看是不是少了什么

**Comment by ChenHao19931** [comment]
谢谢，已经解决了，在相应文件夹下少了scss文件
