### ISSUE TITLE
作业第二步，如何用代码实现找出所有开课的课程？

### ISSUE THREAD

**Issue by tangmaomao16** [PENGZhaoqing/CourseSelect#18]
老师，我已经按提示完成了第一步，add open boolean。但是到第二步，我不知道怎么做？
感觉在代码方面的知识不是很懂。
有没有相关博客讲讲，网站开发里面的那些代码的含义?比如，代码中，有些是下划线连接的几个单词，有些是"a单词.b单词"，这些是什么用意？

**Comment by PENGZhaoqing** [comment]
下划线连接的几个单词只是一个变量，a单词.b单词 代表对 名叫a单词的对象调用名叫b单词的方法

这都是编程常识。。。

**Comment by PENGZhaoqing** [comment]
我只能提示前面

```
   @course=Course.all
   @course=@course-current_user.courses
```

@course里储存了所有的课程，用这个课程减去当前用户已选的课程，等于未选的课程
你再对剩下的课程进行循环找出字段为open的课程，储存到另一个数组里
