### ISSUE TITLE
作业中第一步增加字段问题

### ISSUE THREAD

**Issue by tttrzpt** [PENGZhaoqing/CourseSelect#20]
增加open字段 add_column :open, :boolean, default =>false  // couse表中已经添加了open字段
然后rake db:migrate
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `default' for #<AddOpenAttribute:0x00000002639bb8>

**Comment by PENGZhaoqing** [comment]
`add_column :open, :boolean, :default =>false`

请指定default为符号变量，另外你的这句没有写表名，参考

http://guides.rubyonrails.org/active_record_migrations.html
