### ISSUE TITLE
视图文件中<% %>和<%= %>区别

### ISSUE THREAD

**Issue by baoxin1100** [PENGZhaoqing/CourseSelect#25]
请问什么情况下用<%  %>
什么情况下下用<%=   %>

**Comment by PENGZhaoqing** [comment]
一个简单的例子：

`<%= puts "haha"%>` 会在实际的页面中将haha字符串输出
`<% puts "haha"%>` 只会执行puts "haha"代码，不会在实际的页面中将haha字符串输出

`<% %>` 常用在执行不需要输出的ruby语句，比如判断if else等
`<%= %>` 通常执行ruby语句并输出相关结果

**Comment by baoxin1100** [comment]
get 谢谢助教
