### ISSUE TITLE
form_for语法解释

### ISSUE THREAD

**Issue by terrencestark** [PENGZhaoqing/CourseSelect#27]
form_for本身是个函数，形式为`form_for(record, options = {}, &block)` ，为什么能写为
`form_for @article, url: {action: "create"}, html: {class: "nifty_form"} do |f|`，请问如何理解？
form_for + 空格是怎样的语法，以及用逗号分隔的分别是三个参数吗？
Thanks!

**Comment by PENGZhaoqing** [comment]
一般的ruby方法调用有两种形式，例如`pus new_array`和`puts(new_array)`，ruby为了让代码写起来跟诗一样，即不用括号就可以向方法传递参数，使用空格即可

**Comment by terrencestark** [comment]
好的谢谢。
