### ISSUE TITLE
第二部中的循环条件运行出了问题

### ISSUE THREAD

**Issue by cuifeng1993** [PENGZhaoqing/CourseSelect#29]
代码是这样：
![image](https://cloud.githubusercontent.com/assets/22235079/20554839/6f1d1274-b199-11e6-9a3f-6b826b125918.png)
运行结果是这样：
![image](https://cloud.githubusercontent.com/assets/22235079/20554871/a1cb64fa-b199-11e6-8b62-78ad36299c8f.png)
不明白怎么回事，求指导！

**Comment by PENGZhaoqing** [comment]
你把代码贴上来啊，你这样用图片，我得手动给你转换为代码

**Comment by PENGZhaoqing** [comment]
你的循环差了一个end，只有if的end，循环的end呢？ each_with_index可是一个循环啊

http://apidock.com/ruby/Enumerator/each_with_index

**Comment by PENGZhaoqing** [comment]
因为不能直接给答案，给个例子

```
[11,22,31,224,44].each_with_index do |val,index| 
   puts "index: #{index} for #{val}" 
end
```

val代表数组中的每个元素，index代表每个元素的index

**Comment by cuifeng1993** [comment]
不好意思，今天有事刚回来！谢谢！以后我会给代码的！再次感谢！我再研究研究！
