### ISSUE TITLE
数据库连接问题：PG::ConnectionBad

### ISSUE THREAD

**Issue by cuifeng1993** [PENGZhaoqing/CourseSelect#30]
![image](https://cloud.githubusercontent.com/assets/22235079/20582477/682fd23e-b21c-11e6-9e67-6bbd1019f95c.png)
大神好！我没有对相关的代码进行过修改，这个问题出现了好几次，每次不知道问题在哪里，我都重新建立工作空间，治标不治本！请求帮助！

**Comment by PENGZhaoqing** [comment]
这一看就是数据库没打开,运行`sudo service postgresql start`

**Comment by chengyunguan** [comment]
我也是这个问题，终于解决了

**Comment by qingdujun** [comment]
```
qingdujun@thinkpad:~/pro/CourseSelect$ sudo service postgresql start
qingdujun@thinkpad:~/pro/CourseSelect$ rake db:migrate
**rake aborted!**
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.

```
解决方案：
`sudo apt-get install nodejs`

**Comment by PENGZhaoqing** [comment]
安装的时候需要安装js的运行包,nodejs, 装了吗

![image](https://user-images.githubusercontent.com/11887913/32411529-141daf06-c218-11e7-8517-cd1f46de920f.png)

https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rvm-on-ubuntu-16-04
