### ISSUE TITLE
方法与字段同名如何解决？

### ISSUE THREAD

**Issue by terrencestark** [PENGZhaoqing/CourseSelect#31]

**Comment by terrencestark** [comment]
新建course.open但是执行的时候open被当做private method了。如果说明这是一个字段？

**Comment by terrencestark** [comment]
另外在新的migration文件中用open字段作为添加字段在rake db:migtate的时候文件确实被迁移了，但字段添加没有被执行,schema中也没有增加。

**Comment by PENGZhaoqing** [comment]
方法与字段同名是可以的，private method是因为你定义的open方法前面有个`private`标记了，如：

```
private 

def open
end

def close
end
```
只要是在private后面申明的都是private方法

**Comment by PENGZhaoqing** [comment]
试试`rake db:migrate:reset`

**Comment by terrencestark** [comment]
好的。
