### ISSUE TITLE
open方法有问题

### ISSUE THREAD

**Issue by 5663015** [PENGZhaoqing/CourseSelect#35]
```
def open
    @course=Course.find_by_id(params[:id])
    @course.open_close=true
    @course.save
    redirect_to courses_path, flash: {:success => "已经成功开启该课程:#{ @course.name}"}
  end

def course_params
    params.require(:course).permit(:course_code, :name, :course_type, :teaching_type, :exam_type,
                                   :credit, :limit_num, :class_room, :course_time, :course_week, :open_close)
  end
```
`

![image](https://cloud.githubusercontent.com/assets/8531141/20637574/d87e09ba-b3c6-11e6-8e00-f6450ef4ccef.png)

**Comment by PENGZhaoqing** [comment]
` @course.open_close=true`这句话的意思是，将这个课程对象的open_course属性更新为true，如果这个课程对象为空，那么肯定会报错

你的错误说明了`@course=Course.find_by_id(params[:id])`这句并没有成功获得课程对象，可能是你传入的参数id有问题，比如课程总共只有30个，id从0到29排列，你若要找到id为300的课程那么，就会出现这个错误，nil在ruby代表空的意思

**Comment by 5663015** [comment]
已经解决了，谢谢~

**Comment by cuifeng1993** [comment]
老师，我想问，想你上面提到的，id从0到29排列，那么找到的id怎么会为300呢？麻烦啦！

**Comment by PENGZhaoqing** [comment]
因为id是从请求的url里解析出来的，比如你用浏览器直接访问：`http://localhost:3000/course/300`，在这个url里id就是指的300，而服务器中又不能根据这个id找到对应的数据，所以就会出错，
