### ISSUE TITLE
输入courses/new无法routes到new方法

### ISSUE THREAD

**Issue by chengyunguan** [PENGZhaoqing/CourseSelect#37]
显示`name'是未定义的方法
![image](https://cloud.githubusercontent.com/assets/22127244/20639571/8722af12-b402-11e6-9920-e4bc2a381f23.png)

**Comment by PENGZhaoqing** [comment]
出错的地方在视图文件里，说明找到了Courses控制器和控制器中的new方法，然后也找到了new方法对应的视图，只是在处理视图文件中出现了错误，你这个错误是在`form_for @course`（因为你没贴代码，我也不知道你前面怎么写的）中，@course为空，那么对一个空的对象调用其:name属性肯定报错啊。

检查从控制传过来的@course对象

**Comment by whiteshirt0429** [comment]
_form.html.erb代码

```

<%= form_for @course, html: {class: 'form-horizontal', role: 'form'} do |f| %>

    <div class="form-group">
      <%= f.label "课程名", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :name, class: 'form-control', placeholder: "输入课程名" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "课程属性", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :course_type, class: 'form-control', placeholder: "输入课程属性" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "授课方式", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :teaching_type, class: 'form-control', placeholder: "输入授课方式" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "考试方式", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :exam_type, class: 'form-control', placeholder: "输入考试方式" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "限选人数", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :limit_num, class: 'form-control', placeholder: "输入限选人数" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "课时学分", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :credit, class: 'form-control', placeholder: "输入课时学分" %>
        </div>
      </div>
    </div>


    <div class="form-group">
      <%= f.label "教室", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :class_room, class: 'form-control', placeholder: "输入教室" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "上课周数", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :course_week, class: 'form-control', placeholder: "输入课时学分" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "上课时间", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :course_time, class: 'form-control', placeholder: "输入课时学分" %>
        </div>
      </div>
    </div>

    <%= f.submit '提交', class: "btn btn-success btn-block" %>
    <%= link_to '取消', courses_path, :class => "btn btn-default btn-block" %>

<% end %>



edit.html.erb代码
```
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-3 col-sm-6">
      <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="text-center">更改课程: <%= @course.name %></h3>
        </div>
        <div class="panel-body">
          <%= render "courses/form" %>
        </div>
      </div>
    </div>
  </div>
</div>

```




index.html.erb代码
```
<div class="container-fluid">
  <div class="row">

     <div class="col-md-offset-2 col-sm-8">

      <div class="panel panel-primary">
          <div class="panel-heading">
          <h3 class="panel-title">课程列表</h3>
          </div>
      </div>

        <div class="panel-body">
          <table class="table table-responsive table-condensed table-hover">
            <thead>
            <tr>
              <th>课程编号</th>
              <th>课程名称</th>
              <th>课时/学分</th>
              <th>考试方式</th>
            </tr>

            <tbody>
            <% @course.each do |course| %>
                <tr>
                  <td><%= course.course_code %></td>
                  <td><%= course.name %></td>
                  <td><%= course.credit %></td>
                  <td><%= course.exam_type %></td>
                  <td><%= link_to "编辑", edit_course_path(course), class: 'btn btn-xs btn-info' %></td>
                  <td><%= link_to "删除", course_path(course), :method => "delete", class: 'btn btn-xs btn-danger', :data => {confirm: '确定要删除此课程?'} %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

```

new.html.erb代码


```
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-3 col-sm-6">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="text-center">新课程</h3>
        </div>
        <div class="panel-body">
          <%= render "courses/form" %>
        </div>
      </div>
    </div>
  </div>
</div>

```


courses_controller.rb代码

```
class CoursesController < ApplicationController

  def new
    @course=Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path, flash: {success: "新课程申请成功"}
    else
      flash[:warning] = "信息填写有误,请重试"
      render 'new'
    end
  end

  def edit
    @course=Course.find_by(id: params[:id])
  end

  def update
    @course = Course.find_by_id(params[:id])
    if @course.update_attributes(course_params)
      flash={:info => "更新成功"}
    else
      flash={:warning => "更新失败"}
    end
    redirect_to courses_path, flash: flash
  end

  def destroy
    @course=Course.find_by_id(params[:id])
    @course.destroy
    flash={:success => "成功删除课程: #{@course.name}"}
    redirect_to courses_path, flash: flash
  end

  def index
    @course=Course.all
  end

  private

  def course_params
    params.require(:course).permit(:course_code, :name, :course_type, :teaching_type, :exam_type,
                                   :credit, :limit_num, :class_room, :course_time, :course_week)
  end

end
```

**Comment by newstartcheng** [comment]
我也遇到了同样的问题，请问你最后怎么解决的啊

**Comment by chengyunguan** [comment]
我也遇到了同样的问题，不过我的是找不到class_room，请问你最后怎么解决的啊

**Comment by PENGZhaoqing** [comment]
大多数问题都是，数据库没迁移，rails无法根据这个course这个对象找到数据库相应的字段

`rake db:migrate:reset`
