### ISSUE TITLE
在rails console中如何换行继续输入代码？

### ISSUE THREAD

**Issue by tangmaomao16** [PENGZhaoqing/CourseSelect#38]
老师，我在railstutorial.org网站中看到作者在rails console中输入以下这段代码：
>> s = "foobar"
>> if s.empty?
>>   "The string is empty"
>> else
>>   "The string is nonempty"
>> end
=> "The string is nonempty"

我想问在rails console中如何换行继续输入代码？按哪几个键？

**Comment by PENGZhaoqing** [comment]
控制台没有换行的，你输入回车它就执行一步，但是如果有if这样的语句，就需要有end来结束输入
