### ISSUE TITLE
rake db :migrate出错

### ISSUE THREAD

**Issue by wcyd** [PENGZhaoqing/CourseSelect#39]
def change
    add_column :courses, :open, :boolean
    change_column_default :courses, :open, from: true, to: false
然后rake db :migrate
 (master) $ rake db :migrate
rake aborted!
Don't know how to build task ':migrate' (see --tasks)
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace) 麻烦助教了

**Comment by PENGZhaoqing** [comment]
`rake db:migrate`注意空格

**Comment by wcyd** [comment]
rake db:migrate
== 20161126133112 AddOpenAttributeToCourses: migrating ========================
-- add_column(:courses, :open, :boolean)
   -> 0.1047s
-- change_column_default(:courses, :open, {:from=>true, :to=>false})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type boolean: "---
改了之后，运行出现了这个错误。

**Comment by PENGZhaoqing** [comment]
你的这种带括号的写法，可能格式跟不带括号的不一样：

rails不是提示你带括号的怎么写的么：
change_column_default(:courses, :open, {:from=>true, :to=>false})

**Comment by wcyd** [comment]
我没有带括号啊，最上面提的那个问题里面上面没有带括号。我试了一下，我就算按照这样带括号的写，还是报一样的错误。

**Comment by wcyd** [comment]
我还是不知道，算了我全部重新做了一遍就运行成功了。。。只是为什么错还是不清楚，maybe...
还是辛苦助教了，thanks
