### ISSUE TITLE
有没有rubymine的中文教程

### ISSUE THREAD

**Issue by tangmaomao16** [PENGZhaoqing/CourseSelect#4]
老师，我在ubuntu系统里安装了rubymine2016.2.3，用的是一个月的试用版。但找的一些说明资料都是英文的，而且不是很具体。
老师可不可以，写一个操作过程的例子，比如完成第一次作业，截图，配简要的中文说明？

**Comment by PENGZhaoqing** [comment]
不好意思来晚了，点下面的网址，用学校的邮箱能以学生身份获得Rubymine一年的免费期限：
`https://www.jetbrains.com/ruby/buy/#edition=discounts`

这个作业不着急，都还没拿到课程网站的权限

**Comment by PENGZhaoqing** [comment]
这样吧，你们做一个word，把题号写下来，后面跟着代码和解题思路，最后贴出运行结果（截图即可）。然后再定个时间交上来，不一定是25号

**Comment by PENGZhaoqing** [comment]
http://blog.csdn.net/ppp8300885/article/details/52642839 

Rubymine中文教程 

@tangmaomao16
