### ISSUE TITLE
点击“开课”按钮后，按钮没有更新为“关闭”

### ISSUE THREAD

**Issue by tangmaomao16** [PENGZhaoqing/CourseSelect#42]
我在run网页时，点击“开课”按钮后，按钮没有更新为“关闭”。
我在courses_controller.rb文件中的“开课”的方法代码如下：
```
`  def openc`
    `@course = Course.find_by_id(params[:id])`
   ` @course.open = true`
      `redirect_to courses_path, flash: {:success => "已经成功开启该课程：#{@course.name}"}`
  `end`
```
我想问
（1）`@course.open = true`的写法正确吗？
“@course.open”就表示该课程的open变量，对吗？
给boolean变量赋值，用=，还是用=>?   我在default时用=>，编辑器没有语法错误的红点出现；但是如果写@course.open => true, 编辑器则会有语法错误的红点出现。

（2）`redirect_to courses_path`这句代码，就能使网页进到最新的那个courses_path吗？
如果是最新的话，那open值被赋为true了，结合index.html中的代码，“开课”的按钮应该更新为“关闭”才对。
    我的index.html中的代码如下：
```
`            <% @course.each do |course| %>`
`......`
`         <% if course.open? %>`
                      ` <td><%= link_to "关闭", close_course_path(course), :method => "get", class: 'btn btn-xs btn-warning' %></td>`
                     `  <% else %>`
                     ` <td><%= link_to "开课", openc_course_path(course), :method => "get", class: 'btn btn-xs btn-success' %></td>`
                    `  <% end %>`
`......`
```

**Comment by PENGZhaoqing** [comment]
更新了字段后没有保存，两种写法：
```
@course.open = true
@course.save
```
或者
`
@course.update_attribute!(:open,true)
`

**Comment by PENGZhaoqing** [comment]
https://github.com/PENGZhaoqing/CourseSelect/issues/24

**Comment by PENGZhaoqing** [comment]
![image](https://cloud.githubusercontent.com/assets/11887913/20661729/45ddead2-b58b-11e6-9ae2-f5eff823bc6e.png)

下回提问注意使用工具栏来规范一下格式

**Comment by tangmaomao16** [comment]
老师，请问你是怎么使用这个工具栏的？
我试过先点击Insert code按钮，然后复制粘贴代码到\`\`里面。但是这样Preview显示的代码失去了换行表示，全连在一块了。
后来我就手动地加入多对\`\`，使得Preview显示的代码大致分段了。但是，达不到你帖子内容框里的那种漂亮的效果。

**Comment by 464319127** [comment]
<% if course.open? %>这样写可以吗，我这么写的结果报错：undefined method `open?' for #<Course:0x007fc7a8053558>

**Comment by PENGZhaoqing** [comment]
如果你的数据表里有open这个字段的话，去掉问号试试，open是course的一个字段，调用这个字段返回的是true或者false，你加了问号就变成open?这个没有定义的方法了

`<% if course.open %>`

**Comment by 464319127** [comment]
解决了~谢谢~

**Comment by 464319127** [comment]
解决了~ 谢谢！
