### ISSUE TITLE
js文件加载问题

### ISSUE THREAD

**Issue by 464319127** [PENGZhaoqing/CourseSelect#43]
助教您好。我修改了一个前端模板然后移植到项目中，其中一个关键的js没起作用，请问是跟其中的配置冲突了吗，这个js已经正常加载，控制台也没报错。别的css和js都能正常工作。

<%= javascript_include_tag 'js/custom.min.js' %>

**Comment by 464319127** [comment]
ok~解决了

**Comment by PENGZhaoqing** [comment]
多半是路径问题

**Comment by 464319127** [comment]
放到body前面加载了导致不起作用

**Comment by PENGZhaoqing** [comment]
放在body前面加载js
这种js只在每次全局刷新页面的时候执行，如果只更新局部视图，这种js不会另外执行的
解决方法就是把这种js放到局部视图里加载

**Comment by 464319127** [comment]
get it，谢谢~
