### ISSUE TITLE
link_to中method指定delete问题

### ISSUE THREAD

**Issue by 464319127** [PENGZhaoqing/CourseSelect#45]
助教您好，
我在代码中已经设置了method为delete了，
<%= link_to sessions_logout_path,  method: :delete do %>退出<% end %>
报错是却显示No route matches [GET] "/sessions/logout"
可见是method没有正确设置，不得其解

**Comment by PENGZhaoqing** [comment]
运行`rake routes`，查看路由，贴上来

**Comment by tangmaomao16** [comment]
@464319127 @PENGZhaoqing 你这种`method: :delete do `写法正确吗？
我看原作者的index.html.erb中代码是这样写的：`:method => "delete"`
` <td><%= link_to "删除", course_path(course), :method => "delete", class: 'btn btn-xs btn-danger', :data => {confirm: '确定要删除此课程?'} %></td>`

**Comment by 464319127** [comment]
(in /path/bs/ruby/CourseSelect-master)
              Prefix Verb   URI Pattern                     Controller#Action
         rails_admin        /admin                          RailsAdmin::Engine
                root GET    /                               courses#index
          test_index GET    /test(.:format)                 test#index
                     POST   /test(.:format)                 test#create
            new_test GET    /test/new(.:format)             test#new
           edit_test GET    /test/:id/edit(.:format)        test#edit
                test GET    /test/:id(.:format)             test#show
                     PATCH  /test/:id(.:format)             test#update
                     PUT    /test/:id(.:format)             test#update
                     DELETE /test/:id(.:format)             test#destroy
    select_wn_course GET    /wn_course/:id/select(.:format) wn_course#select
      quit_wn_course GET    /wn_course/:id/quit(.:format)   wn_course#quit
list_wn_course_index GET    /wn_course/list(.:format)       wn_course#list
     wn_course_index GET    /wn_course(.:format)            wn_course#index
                     POST   /wn_course(.:format)            wn_course#create
       new_wn_course GET    /wn_course/new(.:format)        wn_course#new
      edit_wn_course GET    /wn_course/:id/edit(.:format)   wn_course#edit
           wn_course GET    /wn_course/:id(.:format)        wn_course#show
                     PATCH  /wn_course/:id(.:format)        wn_course#update
                     PUT    /wn_course/:id(.:format)        wn_course#update
                     DELETE /wn_course/:id(.:format)        wn_course#destroy
       select_course GET    /courses/:id/select(.:format)   courses#select
         quit_course GET    /courses/:id/quit(.:format)     courses#quit
        list_courses GET    /courses/list(.:format)         courses#list
             courses GET    /courses(.:format)              courses#index
                     POST   /courses(.:format)              courses#create
          new_course GET    /courses/new(.:format)          courses#new
         edit_course GET    /courses/:id/edit(.:format)     courses#edit
              course GET    /courses/:id(.:format)          courses#show
                     PATCH  /courses/:id(.:format)          courses#update
                     PUT    /courses/:id(.:format)          courses#update
                     DELETE /courses/:id(.:format)          courses#destroy
              grades GET    /grades(.:format)               grades#index
               grade PATCH  /grades/:id(.:format)           grades#update
                     PUT    /grades/:id(.:format)           grades#update
               users GET    /users(.:format)                users#index
                     POST   /users(.:format)                users#create
            new_user GET    /users/new(.:format)            users#new
           edit_user GET    /users/:id/edit(.:format)       users#edit
                user GET    /users/:id(.:format)            users#show
                     PATCH  /users/:id(.:format)            users#update
                     PUT    /users/:id(.:format)            users#update
                     DELETE /users/:id(.:format)            users#destroy
      sessions_login GET    /sessions/login(.:format)       sessions#new
                     POST   /sessions/login(.:format)       sessions#create
     sessions_logout DELETE /sessions/logout(.:format)      sessions#destroy

Routes for RailsAdmin::Engine:
    dashboard GET         /                                  rails_admin/main#dashboard
        index GET|POST    /:model_name(.:format)             rails_admin/main#index
          new GET|POST    /:model_name/new(.:format)         rails_admin/main#new
       export GET|POST    /:model_name/export(.:format)      rails_admin/main#export
history_index GET         /:model_name/history(.:format)     rails_admin/main#history_index
  bulk_delete POST|DELETE /:model_name/bulk_delete(.:format) rails_admin/main#bulk_delete
  bulk_action POST        /:model_name/bulk_action(.:format) rails_admin/main#bulk_action
         show GET         /:model_name/:id(.:format)         rails_admin/main#show
         edit GET|PUT     /:model_name/:id/edit(.:format)    rails_admin/main#edit
       delete GET|DELETE  /:model_name/:id/delete(.:format)  rails_admin/main#delete
 history_show GET         /:model_name/:id/history(.:format) rails_admin/main#history_show

**Comment by 464319127** [comment]
```
(in /path/bs/ruby/CourseSelect-master)
              Prefix Verb   URI Pattern                     Controller#Action
         rails_admin        /admin                          RailsAdmin::Engine
                root GET    /                               courses#index
          test_index GET    /test(.:format)                 test#index
                     POST   /test(.:format)                 test#create
            new_test GET    /test/new(.:format)             test#new
           edit_test GET    /test/:id/edit(.:format)        test#edit
                test GET    /test/:id(.:format)             test#show
                     PATCH  /test/:id(.:format)             test#update
                     PUT    /test/:id(.:format)             test#update
                     DELETE /test/:id(.:format)             test#destroy
    select_wn_course GET    /wn_course/:id/select(.:format) wn_course#select
      quit_wn_course GET    /wn_course/:id/quit(.:format)   wn_course#quit
list_wn_course_index GET    /wn_course/list(.:format)       wn_course#list
     wn_course_index GET    /wn_course(.:format)            wn_course#index
                     POST   /wn_course(.:format)            wn_course#create
       new_wn_course GET    /wn_course/new(.:format)        wn_course#new
      edit_wn_course GET    /wn_course/:id/edit(.:format)   wn_course#edit
           wn_course GET    /wn_course/:id(.:format)        wn_course#show
                     PATCH  /wn_course/:id(.:format)        wn_course#update
                     PUT    /wn_course/:id(.:format)        wn_course#update
                     DELETE /wn_course/:id(.:format)        wn_course#destroy
       select_course GET    /courses/:id/select(.:format)   courses#select
         quit_course GET    /courses/:id/quit(.:format)     courses#quit
        list_courses GET    /courses/list(.:format)         courses#list
             courses GET    /courses(.:format)              courses#index
                     POST   /courses(.:format)              courses#create
          new_course GET    /courses/new(.:format)          courses#new
         edit_course GET    /courses/:id/edit(.:format)     courses#edit
              course GET    /courses/:id(.:format)          courses#show
                     PATCH  /courses/:id(.:format)          courses#update
                     PUT    /courses/:id(.:format)          courses#update
                     DELETE /courses/:id(.:format)          courses#destroy
              grades GET    /grades(.:format)               grades#index
               grade PATCH  /grades/:id(.:format)           grades#update
                     PUT    /grades/:id(.:format)           grades#update
               users GET    /users(.:format)                users#index
                     POST   /users(.:format)                users#create
            new_user GET    /users/new(.:format)            users#new
           edit_user GET    /users/:id/edit(.:format)       users#edit
                user GET    /users/:id(.:format)            users#show
                     PATCH  /users/:id(.:format)            users#update
                     PUT    /users/:id(.:format)            users#update
                     DELETE /users/:id(.:format)            users#destroy
      sessions_login GET    /sessions/login(.:format)       sessions#new
                     POST   /sessions/login(.:format)       sessions#create
     sessions_logout DELETE /sessions/logout(.:format)      sessions#destroy

Routes for RailsAdmin::Engine:
    dashboard GET         /                                  rails_admin/main#dashboard
        index GET|POST    /:model_name(.:format)             rails_admin/main#index
          new GET|POST    /:model_name/new(.:format)         rails_admin/main#new
       export GET|POST    /:model_name/export(.:format)      rails_admin/main#export
history_index GET         /:model_name/history(.:format)     rails_admin/main#history_index
  bulk_delete POST|DELETE /:model_name/bulk_delete(.:format) rails_admin/main#bulk_delete
  bulk_action POST        /:model_name/bulk_action(.:format) rails_admin/main#bulk_action
         show GET         /:model_name/:id(.:format)         rails_admin/main#show
         edit GET|PUT     /:model_name/:id/edit(.:format)    rails_admin/main#edit
       delete GET|DELETE  /:model_name/:id/delete(.:format)  rails_admin/main#delete
 history_show GET         /:model_name/:id/history(.:format) rails_admin/main#history_show
```

**Comment by 464319127** [comment]
(in /path/bs/ruby/CourseSelect-master)
              Prefix Verb   URI Pattern                     Controller#Action
         rails_admin        /admin                          RailsAdmin::Engine
                root GET    /                               courses#index
          test_index GET    /test(.:format)                 test#index
                     POST   /test(.:format)                 test#create
            new_test GET    /test/new(.:format)             test#new
           edit_test GET    /test/:id/edit(.:format)        test#edit
                test GET    /test/:id(.:format)             test#show
                     PATCH  /test/:id(.:format)             test#update
                     PUT    /test/:id(.:format)             test#update
                     DELETE /test/:id(.:format)             test#destroy
    select_wn_course GET    /wn_course/:id/select(.:format) wn_course#select
      quit_wn_course GET    /wn_course/:id/quit(.:format)   wn_course#quit
list_wn_course_index GET    /wn_course/list(.:format)       wn_course#list
     wn_course_index GET    /wn_course(.:format)            wn_course#index
                     POST   /wn_course(.:format)            wn_course#create
       new_wn_course GET    /wn_course/new(.:format)        wn_course#new
      edit_wn_course GET    /wn_course/:id/edit(.:format)   wn_course#edit
           wn_course GET    /wn_course/:id(.:format)        wn_course#show
                     PATCH  /wn_course/:id(.:format)        wn_course#update
                     PUT    /wn_course/:id(.:format)        wn_course#update
                     DELETE /wn_course/:id(.:format)        wn_course#destroy
       select_course GET    /courses/:id/select(.:format)   courses#select
         quit_course GET    /courses/:id/quit(.:format)     courses#quit
        list_courses GET    /courses/list(.:format)         courses#list
             courses GET    /courses(.:format)              courses#index
                     POST   /courses(.:format)              courses#create
          new_course GET    /courses/new(.:format)          courses#new
         edit_course GET    /courses/:id/edit(.:format)     courses#edit
              course GET    /courses/:id(.:format)          courses#show
                     PATCH  /courses/:id(.:format)          courses#update
                     PUT    /courses/:id(.:format)          courses#update
                     DELETE /courses/:id(.:format)          courses#destroy
              grades GET    /grades(.:format)               grades#index
               grade PATCH  /grades/:id(.:format)           grades#update
                     PUT    /grades/:id(.:format)           grades#update
               users GET    /users(.:format)                users#index
                     POST   /users(.:format)                users#create
            new_user GET    /users/new(.:format)            users#new
           edit_user GET    /users/:id/edit(.:format)       users#edit
                user GET    /users/:id(.:format)            users#show
                     PATCH  /users/:id(.:format)            users#update
                     PUT    /users/:id(.:format)            users#update
                     DELETE /users/:id(.:format)            users#destroy
      sessions_login GET    /sessions/login(.:format)       sessions#new
                     POST   /sessions/login(.:format)       sessions#create
     sessions_logout DELETE /sessions/logout(.:format)      sessions#destroy

Routes for RailsAdmin::Engine:
    dashboard GET         /                                  rails_admin/main#dashboard
        index GET|POST    /:model_name(.:format)             rails_admin/main#index
          new GET|POST    /:model_name/new(.:format)         rails_admin/main#new
       export GET|POST    /:model_name/export(.:format)      rails_admin/main#export
history_index GET         /:model_name/history(.:format)     rails_admin/main#history_index
  bulk_delete POST|DELETE /:model_name/bulk_delete(.:format) rails_admin/main#bulk_delete
  bulk_action POST        /:model_name/bulk_action(.:format) rails_admin/main#bulk_action
         show GET         /:model_name/:id(.:format)         rails_admin/main#show
         edit GET|PUT     /:model_name/:id/edit(.:format)    rails_admin/main#edit
       delete GET|DELETE  /:model_name/:id/delete(.:format)  rails_admin/main#delete
 history_show GET         /:model_name/:id/history(.:format) rails_admin/main#history_show

**Comment by PENGZhaoqing** [comment]
有可能是符号变量和字符串的问题，试试`method: "delete"`

`method: "delete"` 与 `:method => "delete"`等价

**Comment by 464319127** [comment]
还是不work ,试了网上各种写法都不行，只能先在routes里加个get 'sessions/logout' => 'sessions#destroy'
