### ISSUE TITLE
关于组员在组长项目下贡献度显示的问题

### ISSUE THREAD

**Issue by cuifeng1993** [PENGZhaoqing/CourseSelect#48]
我修改了部分代码，组长也同意了，可是我都不是contributor。。。记得老师说过组长要开什么权限什么的，没研究明白，求指导。。。
![image](https://cloud.githubusercontent.com/assets/22235079/20747554/745f0ecc-b725-11e6-8bc4-4c63639dfa0f.png)
![image](https://cloud.githubusercontent.com/assets/22235079/20747610/ab0f3618-b725-11e6-8ed8-04f4065f0c80.png)

**Comment by PENGZhaoqing** [comment]
如果操作正确，就没有什么问题，可能会有点延迟

**Comment by c2501902968** [comment]
我也存在同样的问题，，，求指导！！！

**Comment by PENGZhaoqing** [comment]
组长正常点那个确认合并就会出现你为贡献者，可能组长在确认的时候用了其他选项了吧

**Comment by c2501902968** [comment]
已解决，谢谢^ω^ 在2016年12月14日 22:07 ，彭兆卿写道： 组长正常点那个确认合并就会出现你为贡献者，可能组长在确认的时候用了其他选项了吧 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
