### ISSUE TITLE
c9 上能用ActionMailer（smtp方式)来发邮件吗？

### ISSUE THREAD

**Issue by xiaokai58** [PENGZhaoqing/CourseSelect#49]
显示说发送成功，但是实际上根本没有收到邮件

**Comment by PENGZhaoqing** [comment]
理论上是可以的，但你需要将各项参数填正确，而且你发送方的邮箱设置比如STMP选项你要打开，第三方登录什么的

https://github.com/PENGZhaoqing/CampusPortal

**Comment by xiaokai58** [comment]
按照https://github.com/PENGZhaoqing/CampusPortal里的配置了下，还是收不到邮件，显示下面的信息这个https://github.com/PENGZhaoqing/CampusPortal在c9上运行能发送邮件吗
UserMailer#welcome_email: processed outbound mail in 198.6ms
Sent mail to xiaok58@163.com (30009.1ms)
Date: Sun, 04 Dec 2016 15:33:05 +0000
From: mxbeijingmi@163.com
To: xiaok58@163.com
Message-ID: <5844373198329_23c83fe80f2a4f1815675@xiaokai58-test4-4114611.mail>
Subject: Welcome to My Awesome Site
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5844373196905_23c83fe80f2a4f18155ac";
 charset=UTF-8
Content-Transfer-Encoding: 7bit

**Comment by PENGZhaoqing** [comment]
从rails的log来看，rails这边是处理OK了，但是呢，邮件是从163发到163，rails只不过是个代理：作为代理登录mxbeijingmi@163.com并向xiaok58@163.com发送邮件，所以最终发送成功没，还是要看163是否能正确处理，我之前也遇见过rails的log显示正确却并没有收到邮件的情况，后来查了好多解决了，然后又出问题了。。。企业邮箱应该好点

你应该把你的配置信息贴出来

**Comment by xiaokai58** [comment]
在development.rb文件中：
Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.
 #config.action_mailer.default_url_options = {host: 'ucas-portal.herokuapp.com'}

  config.action_mailer.perform_deliveries = true
  config.action_mailer.delivery_method = :smtp
  ActionMailer::Base.smtp_settings = {
      :address => 'smtp.163.com',
      :port => '25',
      :authentication => :login,
      :user_name => ENV['mxbeijingmi@163.com'],
      :password => ENV['menxu0725'],
      :domain => 'www.163.com',
      :enable_starttls_auto => true
  }
在production.rb文件中：
Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.
 #config.action_mailer.default_url_options = {host: 'ucas-portal.herokuapp.com'}

  config.action_mailer.perform_deliveries = true
  config.action_mailer.delivery_method = :smtp
  ActionMailer::Base.smtp_settings = {
      :address => 'smtp.163.com',
      :port => '25',
      :authentication => :login,
      :user_name => ENV['mxbeijingmi@163.com'],
      :password => ENV['menxu0725'],
      :domain => 'www.163.com',
      :enable_starttls_auto => true
  }

在application_mailer.rb文件中：
class ApplicationMailer < ActionMailer::Base
  default from: "mxbeijingmi@163.com"
  layout 'mailer'
end

**Comment by PENGZhaoqing** [comment]
![image](https://cloud.githubusercontent.com/assets/11887913/20873709/6dceee10-bae5-11e6-88a1-bde468459086.png)

发送方的邮箱设置设置没

**Comment by xiaokai58** [comment]
嗯，发送方和接收方的邮箱的都设置了

**Comment by PENGZhaoqing** [comment]
```
   config.action_mailer.default_url_options = {host: 'your_site_domain.com'}

   config.action_mailer.perform_deliveries = true
   config.action_mailer.delivery_method = :smtp


   ActionMailer::Base.smtp_settings = {
       :address => 'smtp.163.com',
       :port => '25',
       :authentication => :login,
       :user_name => ENV['163MAIL_USERNAME'],
       :password => ENV['163MAIL_PASSWORD'],
       :domain => 'www.163.com',
       :enable_starttls_auto => true
   }
```

your_site_domain.com填的什么
另外你关于发送邮件的控制器和视图贴上来

**Comment by xiaokai58** [comment]
` config.action_mailer.default_url_options = { host: '127.0.0.1', port: 3000 }`


![g1](https://cloud.githubusercontent.com/assets/22228958/20876694/b999628a-bafe-11e6-9f65-3b08a4268557.png)


发送的地方
![image](https://cloud.githubusercontent.com/assets/22228958/20876723/eea9642a-bafe-11e6-8741-ecaa2c80a6fb.png)

视图：
![image](https://cloud.githubusercontent.com/assets/22228958/20876788/5284fb58-baff-11e6-8e73-8a1983e69c1c.png)

**Comment by PENGZhaoqing** [comment]
`config.action_mailer.default_url_options = { host: '127.0.0.1', port: 3000 }`

127.0.0.1是本地开发用的测试地址，c9肯定不能写这个啊，要写你的project网址url

http://stackoverflow.com/questions/30395432/rails-sending-email-after-filling-contact-form

**Comment by xiaokai58** [comment]
![image](https://cloud.githubusercontent.com/assets/22228958/20884158/9993a3da-bb24-11e6-87f6-04498a0a5d34.png)
是这样设置吗：config.action_controller.default_url_options = {:host => " https://test4-xiaokai58.c9users.io"}

**Comment by xiaokai58** [comment]
![image](https://cloud.githubusercontent.com/assets/22228958/20884416/1fc586c0-bb26-11e6-86f6-a8424b9162f4.png)
config.action_mailer.default_url_options = {:host => "https://test4-xiaokai58.c9users.io", :port => "3000"}
这样设置？

**Comment by PENGZhaoqing** [comment]
3000也是本地的端口，可以不写，因为我也不知道端口是多少，可能是8080，不写应该就是默认的

怎么设置我也说了也不算，你大胆就尝试就行了，试对了就对了
