### ISSUE TITLE
c9注册

### ISSUE THREAD

**Issue by weilai1** [PENGZhaoqing/CourseSelect#5]
请问，c9注册除了用信用卡，还有其他方法吗？谢谢

**Comment by PENGZhaoqing** [comment]
在下面网址中注册，然后点击选修这门课程：

`https://www.edx.org/course/introduction-computer-science-harvardx-cs50x`

**Comment by PENGZhaoqing** [comment]
然后访问这个网址：`cs50.io`，点击提交

**Comment by PENGZhaoqing** [comment]
会让你再次输入一遍刚才注册的账号密码，输入正确后，直接进入c9的一个workspace
