### ISSUE TITLE
除了用btn-info和btn-danger，怎么修改按钮颜色？

### ISSUE THREAD

**Issue by cuifeng1993** [PENGZhaoqing/CourseSelect#51]
老师你好，我知道代码中的btn-info，和btn-danger会使按钮成下面图中的蓝色和红色
```
<td><%= link_to "编辑", edit_course_url(course), class: 'btn btn-xs btn-info' %></td>

<td><%= link_to "删除", course_path(course), :method => "delete", class: 'btn btn-xs btn-danger', :data => {confirm: '确定要删除此课程?'} %></td>
```

![image](https://cloud.githubusercontent.com/assets/22235079/20961479/2ded258e-bca0-11e6-8cce-8cca87e3471f.png)

老师在作业演示中给出的“关闭”可以是黄色，如图

![image](https://cloud.githubusercontent.com/assets/22235079/20961508/4fd2e27e-bca0-11e6-9756-e441a08f7263.png)

我想问这个按钮的颜色是怎么控制的？

**Comment by PENGZhaoqing** [comment]
这个是因为你导入了bootsrap的前端库，这个库已经定义了所有`class=“btn-info”`的html元素的颜色为蓝色
还有其他颜色，请参考：http://www.w3schools.com/bootstrap/bootstrap_buttons.asp

需要翻墙
