### ISSUE TITLE
如何退出git pull合并需要编辑的vim界面

### ISSUE THREAD

**Issue by 5663015** [PENGZhaoqing/CourseSelect#54]
输入git pull时出现下面情况：
![image](https://cloud.githubusercontent.com/assets/8531141/21013128/cf3026dc-bd93-11e6-87df-43c2a778ce25.png)

输入git add *          git commit -m""      git push origin master 这几个命令时出现下面情况：
![image](https://cloud.githubusercontent.com/assets/8531141/21013146/ddb0e638-bd93-11e6-9d24-3f60904dab59.png)

**Comment by PENGZhaoqing** [comment]
因为远程端修改了，然后你本地端也改了，两者有冲突，现在你git pull拉下来有冲突（强行合并），需要你编辑一下合并的理由和修改的内容，这个界面是linux的vi编辑器

按ECS回到非输入状态，输入`:wq`回车退出

**Comment by 5663015** [comment]
我按ESC退出不了啊，没有反应，缺少什么东西吗？

**Comment by 5663015** [comment]
还有就是，我的组员几乎同时向我提交了pull requests，会有冲突吗

**Comment by PENGZhaoqing** [comment]
基本上不会同时，就算是同时点击，请求之间因为网络状态也会相差1ms甚至更多，所以还是有个处理的顺序的

**Comment by PENGZhaoqing** [comment]
按ECS回到非输入状态，这个时候你是无法输入的，然后`Shift+冒号`输入`:`，你就会看到有输入框，你继续打入`wq`回车退出
