### ISSUE TITLE
在User类里如何区分teacher, student, admin三种角色的用户

### ISSUE THREAD

**Issue by tangmaomao16** [PENGZhaoqing/CourseSelect#58]
老师，你的选课系统中，models文件夹中，只有一个user.rb文件，并没有用teacher, student, admin三个.rb文件去继承User类。请问你是怎么实现对teacher, student, admin这三种用户的区分处理的呢？
你认为多建立三个子类好吗？可以吗？

**Comment by PENGZhaoqing** [comment]
User类对应的users数据表中有两个字段

 ```
     t.boolean :admin, default: false
     t.boolean :teacher, default: false
```

其实创建都是user对象，只是用字段区分角色的不同，还没有到继承那么复杂
