### ISSUE TITLE
教程一在最后运行的时候出现的问题，谢谢

### ISSUE THREAD

**Issue by sdzbzj0406** [PENGZhaoqing/CourseSelect#6]
Started GET "/" for 111.195.215.172 at 2016-09-23 16:52:56 +0000
Cannot render console from 111.195.215.172! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Rails::WelcomeController#index as HTML
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/templates/rails/welcome/index.html.erb (121.0ms)

**Comment by PENGZhaoqing** [comment]
你是点的`run project`自动运行的，还是手动使用指令`rails server`运行的？

**Comment by sdzbzj0406** [comment]
我点的是run project 

张杰

**Comment by PENGZhaoqing** [comment]
你先看一下这个网址：

https://community.c9.io/t/cannot-render-from-console/1385

如果还是不行的话，在终端手动运行：`rails s -b $IP -p $PORT`

如果还是不行，删掉这个project，重新再来一遍，一般不可能出现这种问题的。

**Comment by sdzbzj0406** [comment]
老师，能给我推荐几本ruby和ROR的书吗，我想系统的学一学，在线学习的感觉不是很好。谢谢老师

张杰

**Comment by PENGZhaoqing** [comment]
https://www.railstutorial.org/book/beginning

这本书对在Rails实战方面讲的很好，跟着这本书走完，能做出比我这个项目更好的

Ruby语言其实不用过多学习，在下面这个网址中了解基本语法就ok了：

http://www.runoob.com/ruby/ruby-tutorial.html

**Comment by sdzbzj0406** [comment]
好的，非常感谢

张杰
