### ISSUE TITLE
关于在rails视图中使用二维数组

### ISSUE THREAD

**Issue by 464319127** [PENGZhaoqing/CourseSelect#61]
我在视图上这么写的：
 
![image](https://cloud.githubusercontent.com/assets/8693709/21384048/a2543972-c7a3-11e6-9eff-a50b8199ba7c.png)

控制器：
![image](https://cloud.githubusercontent.com/assets/8693709/21384034/93dd3ace-c7a3-11e6-930a-386c7c78d369.png)

显示效果：
![image](https://cloud.githubusercontent.com/assets/8693709/21384063/b1f5d052-c7a3-11e6-8f01-819674a81c4e.png)

只循环了两次，感觉很奇怪。
另外想请教一下ruby二维数组的正确定义方法~谢谢~

**Comment by PENGZhaoqing** [comment]
你就定义了`[[],[]]`一个只有两行的二维数组，输出的时候当然是只有两次循环了

参考：

http://stackoverflow.com/questions/1720932/create-two-dimensional-arrays-and-access-sub-arrays-in-ruby

http://stackoverflow.com/questions/7014052/ruby-multidimensional-array

**Comment by 464319127** [comment]
好的~~谢谢~~~
