### ISSUE TITLE
请问如何将数据导入到数据库中

### ISSUE THREAD

**Issue by c2501902968** [PENGZhaoqing/CourseSelect#64]
我新建了一个model想要存储课程的详细信息，但是如何将整理好的这些数据导入到数据库里面，是需要写种子文件么？

**Comment by PENGZhaoqing** [comment]
一种方式就是手动在网页上一条一条添加

如果需要批量导入，需要写编写seed.rb文件

**Comment by c2501902968** [comment]
好的，谢谢 在2016年12月28日 14:09 ，彭兆卿写道： 一种方式就是手动在网页上一条一条添加 如果需要批量导入，需要写编写seed.rb文件 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
