### ISSUE TITLE
导出课程列表的时候提示路由错误

### ISSUE THREAD

**Issue by tttrzpt** [PENGZhaoqing/CourseSelect#67]
`<td><%= link_to "导出",course_path(:format => :xls), class: 'btn btn-xs btn-danger', :data => {confirm: '确定要导出课程列表?'} %></td>`
我用的to_xls插件，路由里面export也设置成了post不知道怎么改了。。。

**Comment by PENGZhaoqing** [comment]
你可以用一个新的路由为 `export: get`, 用`rake routes`查看你新路由的调用方法，假设为course_export_path

那么course_export_path(:format => :xls)能够正确提交到Course类的export方法里，在这个方法里做to_xls的相关操作

**Comment by tttrzpt** [comment]
谢谢助教，搞定了。。。。
![t8uaau_9assy0s9 hq 880](https://cloud.githubusercontent.com/assets/12119736/21585979/aacedc54-d105-11e6-9ef6-f0c094f2a05a.png)
