### ISSUE TITLE
关于删除选课的参数问题

### ISSUE THREAD

**Issue by ZhouHonghao** [PENGZhaoqing/CourseSelect#68]
助教您好。我有两个问题：
第一个问题：
在原版的选课系统中，关于学生退课的cotroller是这样的：
  ```
def quit
    @course=Course.find_by_id(params[:id])
    current_user.courses.delete(@course)
    flash={:success => "成功退选课程: #{@course.name}"}
    redirect_to courses_path, flash: flash
  end
```
而在view中是这样的：
```
<% elsif student_logged_in? %>
     <td><%= link_to "删除", quit_course_path(course), class: 'btn-sm btn-danger' %></td>
 <% end %>
```

请问quit_course_path(course)为什么有参数course，在定义quit的时候参数是空的？

第二个问题：
我想做一个批量退课功能，即做一个多选框，选中多项后，点击退课按钮，一次退选多门课。但我不知道controller和view之间的参数应该如何传递？

view:
```
<% @course.each do |course| %>
...<%= check_box_tag "course_ids[]", course.id %>...
<% end %>
...
<%= link_to "删除", destroy_multiple_courses_path, class: 'btn-sm btn-danger' %>
```

controller:
```
def destroy_multiple
  respond_to do |format| if not params[:course_id] .nil?
    begin
      Course.transaction do
         params[:course_id].each do |did|
          if did != ""
            @course = courses.find(did)
            @course.destroy
          end
    end
  end
  flash[:notice] = "删除数据成功！"
  rescue 
    flash[:notice] = "删除数据失败！" 
    end
  else
    flash[:notice] = '请选择要删除的课程！'
  end
  format.html { redirect_to(courses_url) }
  format.xml  { head :ok }
  end
end
```

**Comment by PENGZhaoqing** [comment]
问题1.

quit_course_path(course)传入的是当前选中的课程，rails会自动将此课程的id写入，那么在控制器中能通过params[:id]把这个课程的id取出来

问题2.

想法很好，但是这样的多选项操作一般由html+js完成，当用户点击按钮后，用js来收集被选中的课程的id，放到一个数组里，提交这个数组到控制器中，然后在这个数组中循环删除就可以了

难度比加大，可能会涉及js的ajax提交

**Comment by PENGZhaoqing** [comment]
http://stackoverflow.com/questions/5866169/getting-all-selected-values-of-a-multiple-select-box-when-clicking-on-a-button-u

**Comment by ZhouHonghao** [comment]
好的，谢谢您。

**Comment by ZhouHonghao** [comment]
助教您好，我按照您上次的建议写了一段收集选中id的脚本，但不知道如何将脚本所收集的course_ids数组传到后台？
```
function ids_checked(){
      var courses = document.getElementsByTagName('input');
      var course_ids = new Array();
      for(var i = 0; i < courses.length; i++){
         if(courses[i].checked)
			   course_ids.push(courses[i].id);
      }  
    }  
}
```
谢谢。

**Comment by PENGZhaoqing** [comment]
我这里有一段代码，功能同样是点击某个按钮后，通过js收集信息然后提交此表单

https://github.com/PENGZhaoqing/CampusPortal/blob/master/app/views/access/edit.html.erb

**Comment by ZhouHonghao** [comment]
助教您好。因为我对您的上面一段脚本代码不熟，所以我想了一个不太好的方法，仅仅想试一下，但仍然没有运行。我知道这种方法在现实工程中是不可能用的，但我想知道能不能运行，我的问题出在哪。

首先，我在网页中定义了一个Array对象。<% coursechecked = Array.new %>
然后，每次复选框被选中，这一行的course就被push到coursechecked中。
<td><%= check_box_tag course.course_code.to_s, course.id %></td>                  
<% if check_box_tag(course.id) == true %>
  <% coursechecked.push(course) %>
<% end %>
接下来，我用link_to，把收集到的course传到后台。
<%= link_to "删除选中课程", destroy_multiple_courses_path, {:coursec => coursechecked, class: 'btn-sm btn-danger'} %>
controller部分：
*@coursec =  params[:coursechecked] #q2.这种传参方式我不知道对不对
最后一步，循环quit:
@coursec.each do |c|
   quit(c) #q3.这一步，我对传参理解的不好
   # 实际上，不管q1和q2那两个地方有没有解决，程序真的走到这里了，然后在find_by_id里出错了
end

我想知道这种方案能否当做试验给运行成功；关于标注的q1,q2,q3这三个地方哪里出错；出错的地方，能否解决。

谢谢您的帮助。

**Comment by ZhouHonghao** [comment]
（上面那段太乱了，重发一遍）
助教您好。因为我对您的上面一段脚本代码不熟，所以我想了一个不太好的方法，仅仅想试一下，但仍然没有运行。我知道这种方法在现实工程中是不可能用的，但我想知道能不能运行，我的问题出在哪。

首先，我在网页中定义了一个Array对象。<% coursechecked = Array.new %>
然后，每次复选框被选中，这一行的course就被push到coursechecked中。

<%= check_box_tag course.course_code.to_s, course.id %> <% if check_box_tag(course.id) == true %> <% coursechecked.push(course) %> <% end %> 

接下来，我用link_to，把收集到的course传到后台。 <%= link_to "删除选中课程", destroy_multiple_courses_path, {:coursec => coursechecked, class: 'btn-sm btn-danger'} %>
 controller部分： 
*@coursec = params[:coursechecked] #q2.这种传参方式我不知道对不对 

最后一步，循环quit: 
@coursec.each do |c| 
  quit(c)  #q3.这一步，我对传参理解的不好 
  # 实际上，不管q1和q2那两个地方有没有解决，程序真的走到这里了，然后在find_by_id里出错了 
end

我想知道这种方案能否当做试验给运行成功；关于标注的q1,q2,q3这三个地方哪里出错；出错的地方，能否解决。

谢谢您的帮助。

**Comment by ZhouHonghao** [comment]
助教您好。因为我对您的上面一段脚本代码不熟，所以我想了一个不太好的方法，仅仅想试一下，但仍然没有运行。我知道这种方法在现实工程中是不可能用的，但我想知道能不能运行，我的问题出在哪。

首先，我在网页中定义了一个Array对象。<% coursechecked = Array.new %>
然后，每次复选框被选中，这一行的course就被push到coursechecked中。

<%= check_box_tag course.course_code.to_s, course.id %> <% if check_box_tag(course.id) == true %> <% coursechecked.push(course) %> <% end %>

接下来，我用link_to，把收集到的course传到后台。 <%= link_to "删除选中课程", destroy_multiple_courses_path, {:coursec => coursechecked, class: 'btn-sm btn-danger'} %>
controller部分：
*@coursec = params[:coursechecked] #q2.这种传参方式我不知道对不对

最后一步，循环quit:
@coursec.each do |c|
  quit(c) #q3.这一步，我对传参理解的不好
  #实际上，不管q1和q2那两个地方有没有解决，程序真的走到这里了，然后在find_by_id里出错了
end

我想知道这种方案能否当做试验给运行成功；关于标注的q1,q2,q3这三个地方哪里出错；出错的地方，能否解决。

谢谢您的帮助。

**Comment by ZhouHonghao** [comment]
助教您好。因为我对您的上面一段脚本代码不熟，所以我想了一个不太好的方法，仅仅想试一下，但仍然没有运行。我知道这种方法在现实工程中是不可能用的，但我想知道能不能运行，我的问题出在哪。

首先，我在网页中定义了一个Array对象。<% coursechecked = Array.new %>
然后，每次复选框被选中，这一行的course就被push到coursechecked中。

```
<%= check_box_tag course.course_code.to_s, course.id %>
 <% if check_box_tag(course.id) == true %> 
<% coursechecked.push(course) %>
 <% end %>
```
（q1.这个判断我觉得有问题）

接下来，我用link_to，把收集到的course传到后台。

` <%= link_to "删除选中课程", destroy_multiple_courses_path, {:coursec => coursechecked, class: 'btn-sm btn-danger'} %>`

controller部分：

`*@coursec = params[:coursechecked] #q2.这种传参方式我不知道对不对`

最后一步，循环quit:
`@coursec.each do |c|`
quit(c) #q3.这一步，我对传参理解的不好

#实际上，不管q1和q2那两个地方有没有解决，程序真的走到这里了，然后在find_by_id里出错了
end

我想知道这种方案能否当做试验给运行成功；关于标注的q1,q2,q3这三个地方哪里出错；出错的地方，能否解决。

谢谢您的帮助。

**Comment by PENGZhaoqing** [comment]
问题很多啊，首先q1不太可能实现，html只在页面刷新完后就不会变了，你期望的是每次复选框被选中然后触发一定的动作，必须得借助js，让js脚本不断监听当前页面的变化才能实现，html只是标记语言，那个if判断只会在每次页面刷新的时候才会执行？

q2是想把数组传进控制器，但是语法有问题

q3就是把这个数组做循环，找每个课程，然后退课，思路对的

难点就在q1和q3，如何通过js把页面的变化获得然后交给html的form，然后点击按钮提交到后台

**Comment by ZhouHonghao** [comment]
好的，感谢助教。这一次我终于对动态静态这两个概念有深刻认识了。
谢谢您这个学期为大家答疑解惑。有机会继续向您学习。:)
