### ISSUE TITLE
教程二中语法错误

### ISSUE THREAD

**Issue by gaolou16** [PENGZhaoqing/CourseSelect#7]
`has_many :teaching_courses, class_name:"Course", foreign_key::teacher_id`
教程二中这句代码一直报错，是照着教程上编写的，没有敲错
提示错误是
`syntax error, unexpected '\n', expecting =>`

**Comment by PENGZhaoqing** [comment]
在 `foreign_key::teacher_id`这一句中，加个空格，如下：
`foreign_key: :teacher_id`

**Comment by PENGZhaoqing** [comment]
如果不行，可以换成下面的写法：
`:foreign_key => :teacher_id`

**Comment by LightCastlePro** [comment]
you are 666
