### ISSUE TITLE
github在pull request时出现conflict

### ISSUE THREAD

**Issue by chengyunguan** [PENGZhaoqing/CourseSelect#70]
![image](https://cloud.githubusercontent.com/assets/22127244/21591641/f580117e-d140-11e6-9ca4-dae4bd141d41.png)

这种情况下merge按钮是灰色的不能点，要如何让发起pull request的成员改自己的代码才能重新提交pull request成功

**Comment by PENGZhaoqing** [comment]
让他们自己在本地去git pull你主分支的代码，然后再pull request过来
