### ISSUE TITLE
查询数据库的问题

### ISSUE THREAD

**Issue by myprayer2015** [PENGZhaoqing/CourseSelect#72]
undefined method `student_num' for #<Course:0x007fe4863c7040>
源码如下：
<td><%= course.student_num %></td>

course中有student_num属性  但是却提示错误

这个功能时好时坏   有时候就可以正常使用

**Comment by PENGZhaoqing** [comment]
信息太少，无法判断

下次出现错误后，推荐使用`rails console`命令进入rails的命令行模式，手动输入ruby代码查看这个字段：
```
course=Course.find_by_id(出错的课程id)
puts course.student_num
```
