### ISSUE TITLE
form表单submit按钮无法提交，除非刷新一次

### ISSUE THREAD

**Issue by 5663015** [PENGZhaoqing/CourseSelect#76]
![image](https://cloud.githubusercontent.com/assets/8531141/21651574/1578065e-d2e4-11e6-8b86-ae7c398d3ccb.png)
当用户第一次到这个页面时，点击查询按钮没有任何反应，刷新后就可以提交了。这是怎么回事？
视图代码：

![image](https://cloud.githubusercontent.com/assets/8531141/21651819/1c9eed8e-d2e5-11e6-9d30-ed6fce22495e.png)
这段代码总是粘贴不过来，只能截图了，不好意思
控制器代码：
```
def list
    @q1=params[:name]
    if @q1.nil? == false 
      @course = Course.where("name like '%#{@q1}%' ")
    else
      @course=Course.all
    end
```
……

**Comment by PENGZhaoqing** [comment]
浏览器F12进入开发模式，查看console控制台有没有错误输出

**Comment by 5663015** [comment]
![image](https://cloud.githubusercontent.com/assets/8531141/21678157/868f9002-d378-11e6-9ab1-df530309df50.png)
这样吗？没有任何输出

**Comment by PENGZhaoqing** [comment]
这个我也不清楚了，除非我能操作你的电脑。。换个浏览器试试
