### ISSUE TITLE
sudo service postgrsql start 出现问题

### ISSUE THREAD

**Issue by xiechengliang4** [PENGZhaoqing/CourseSelect#77]
在c9终端中输入sudo service postgrsql start 出现了下面这个问题
>>> /etc/sudoers: syntax error near line 15 <<<
sudo: parse error in /etc/sudoers near line 15
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

**Comment by PENGZhaoqing** [comment]
https://community.c9.io/t/etc-sudoers-syntax-error-near-line-15/12582

C9的bug，等等看
