### ISSUE TITLE
heroku 部署的问题

### ISSUE THREAD

**Issue by myprayer2015** [PENGZhaoqing/CourseSelect#79]
FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege

PG::ConnectionBad: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.

提示这个  很懵的状态

**Comment by PENGZhaoqing** [comment]
postgresql数据库登陆有不同的用户，问题可能是你现在操作的用户没有这个权限，数据库的超级用户是postgres，我看不到你到底执行的是什么操作，所以给出几个连接：


http://stackoverflow.com/questions/18972829/rake-dbreset-user-does-not-have-connect-privilege

http://stackoverflow.com/questions/27846844/heroku-schema-load-permission-denied-for-database-postgres-user

翻墙后用google搜索，会有很多debug提示
