### ISSUE TITLE
最后运行时出现的问题

### ISSUE THREAD

**Issue by 5663015** [PENGZhaoqing/CourseSelect#8]
点运行后，打开页面是这样的：
![image](https://cloud.githubusercontent.com/assets/8531141/18938180/51b6f150-8629-11e6-9171-0f0a55d1331c.png)
这怎么解决啊，谢谢~

**Comment by PENGZhaoqing** [comment]
这个是没有建表。。

运行 `rake db:migrate`

**Comment by 5663015** [comment]
当我运行rake db:create:all时出现了：
PG::InvalidCatalogName: ERROR:  template database "template1" does not exist
: CREATE DATABASE "courseselect_development" ENCODING = 'unicode'
……
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"courseselect_development"}
PG::InvalidCatalogName: ERROR:  template database "template1" does not exist
: CREATE DATABASE "courseselect_test" ENCODING = 'unicode'
……
运行rake db:migrate时出现：
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "courseselect_development" does not exist
……
然后运行rake db:seed同样的问题。
结果运行这样：
![image](https://cloud.githubusercontent.com/assets/8531141/18941922/cc6a1d28-8647-11e6-8576-7aaec4b0e6f5.png)

**Comment by PENGZhaoqing** [comment]
切换postgres用户 : `sudo -i -u postgres`

然后进入数据库： `psql`

手动创建template1：`create database template1 TEMPLATE postgres;`

运行`\q`退出数据库

reference： http://stackoverflow.com/questions/27992560/template0-and-template1-database-dropped-accidently

若还是不行，qq我
