### ISSUE TITLE
gem install nokogiri -v '1.6.8'

### ISSUE THREAD

**Issue by qingdujun** [PENGZhaoqing/CourseSelect#81]
执行`bundle install`时报错。

qingdujun@thinkpad:~/pro/CourseSelect$ **bundle install**
```
//...
`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`
//...
An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.
```
qingdujun@thinkpad:~/pro/CourseSelect$ **sudo gem install nokogiri -v '1.6.8'**
```
Building native extensions.  This could take a while...
//...
ERROR:  Error installing nokogiri:
ERROR: Failed to build gem native extension.

```
我可以删除Gemfile.lock吗？

解决方案：
```
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
gem install nokogiri
```

now, everything is ok!

but, another question.....

An error occurred while installing pg (0.18.4), and Bundler cannot
continue.
Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.

解决方案：
```
sudo apt-get install libpq-dev
sudo gem install pg
```

**Comment by PENGZhaoqing** [comment]
Gemfile.lock是rails自己管理的,你不用管他
